src/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

from userena import views as userena_views
from userena.forms import mSignupForm

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^accounts/', include('userena.urls')),
    url(r'/admintools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', userena_views.signup, {'signup_form': mSignupForm}),
    url(r'^news/', include('news.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^traffic/', include('haram_traffic.urls')),
    )

urlpatterns += staticfiles_urlpatterns()

src/userena/contrib/umessages/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

from userena.contrib.umessages import views as messages_views

urlpatterns = patterns('',
    url(r'^compose/$',
        messages_views.message_compose,
        name='userena_umessages_compose'),

    url(r'^compose/(?P<recipients>[\+\.\w]+)/$',
        messages_views.message_compose,
        name='userena_umessages_compose_to'),

    url(r'^reply/(?P<parent_id>[\d]+)/$',
        messages_views.message_compose,
        name='userena_umessages_reply'),

    url(r'^view/(?P<username>[\.\w]+)/$',
        messages_views.message_detail,
        name='userena_umessages_detail'),

    url(r'^remove/$',
        messages_views.message_remove,
        name='userena_umessages_remove'),

    url(r'^unremove/$',
        messages_views.message_remove,
        {'undo': True},
        name='userena_umessages_unremove'),

    url(r'^$',
        messages_views.message_list,
        name='userena_umessages_list'),
)

src/userena/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from userena import views as userena_views
from userena import settings as userena_settings
from forms import mSignupForm

urlpatterns = patterns('',
    # Signup, signin and signout
  
  
   url(r'^signup/$',
    userena_views.signup,
    {'signup_form': mSignupForm}),
    
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       auth_views.logout,
       {'next_page': userena_settings.USERENA_REDIRECT_ON_SIGNOUT,
        'template_name': 'userena/signout.html'},
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^(?P<username>[\.\w]+)/activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.profile_list,
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.profile_list,
       name='userena_profile_list'),
)

src/users/models.py
from django.db import models
from userena.models import UserenaBaseProfile
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from datetime import datetime
from easy_thumbnails.fields import ThumbnailerField
from django.contrib.auth.models import User


#class Country(models.Model):
#    name = models.CharField(_('Name'),  max_length=30 , default= "Egypt")
#    class Meta:
#        verbose_name        = _('Country')
#        verbose_name_plural = _('Countries')
#
#    def __unicode__(self):
#        return self.name

class Media(models.Model):
    
    IMAGE_TYPE = 0
    VIDEO_TYPE = 1
    TYPES = (
                (IMAGE_TYPE, _('image')),
                (VIDEO_TYPE, _('video'))
             )

    type = models.IntegerField(_("Media Type"), max_length=1, choices=TYPES)
    item_name = models.CharField(_("Name"), help_text=_("Media Item name"), max_length=100)
    add_time = models.DateTimeField(_("Time"), help_text=_("Addition time"), default=datetime.now())
    item_file_name = ThumbnailerField(_("File name"), help_text=_("Media item file name"), upload_to="media_items")
    
    def __unicode__(self):
        return self.item_name

    class Meta:
        verbose_name = _('Media Item')
        verbose_name_plural = _('Media Items')


class Notification(models.Model):
    MORAL_PREPARATION = 0
    PHYSICAL_PREPARATION = 1
    TRAVELING_DAY = 2
    IHRAM_HOW = 3
    IHRAM_TABOO = 4
    ENTERING_MEKKA = 5
    UMRAH = 6
    CATEGORIES = (
                  (MORAL_PREPARATION, _('moral preparation')),
                  (PHYSICAL_PREPARATION , _('physical preparation')),
                  (TRAVELING_DAY , _('traveling day')),
                  (IHRAM_HOW , _('ihram how')),
                  (IHRAM_TABOO , _('ihram taboo')),
                  (ENTERING_MEKKA , _('entering mekka')),
                  (UMRAH, _('umrah')),
                  )
    BOTH = 0
    MALE = 1
    FEMALE = 2
    WHOM = (
            (BOTH, _('both')),
            (MALE, _('male')),
            (FEMALE, _('female')),
            )
    NOT_DEFINED = 0
    EIGHTH = 1
    NINTH = 2
    TENTH = 3
    ELEVNTH = 4
    TWELVTH = 5
    THIRTEENTH = 6
    DAYS = (
            (NOT_DEFINED, _('not defined')),
            (EIGHTH, _('egihth')),
            (NINTH, _('ninth')),
            (TENTH, _('tenth')),
            (ELEVNTH, _('eleventh')),
            (TWELVTH, _('twelvth')),
            (THIRTEENTH, _('thirteenth')),
            )
    TAMATTO3 = 0
    EFRAD = 1
    KERAN = 2
    HAJJ_TYPES = (
                  (TAMATTO3, _('tamato3')),
                  (EFRAD, _('efrad')),
                  (KERAN, _('keran')),
                  )

    title = models.CharField(_('title'), max_length=60, db_index=True)
    title_en = models.CharField(_('title en'), max_length=60, db_index=True)
    message = models.TextField(_("Message"), max_length=1023,
                               help_text=_("Message sent to the person"))
    message_en = models.TextField(_("Message en"), max_length=1023,
                               help_text=_("Message sent to the person"))
#    time = models.DateTimeField(_("Time"), help_text=_("When to send this message") , default=datetime.now())
    category = models.IntegerField(_('category'),
                                   help_text=('it is relative to manasek start date'), choices=CATEGORIES)
    which_day = models.IntegerField(_('which day'), choices=DAYS)
    hajj_type = models.IntegerField(_('hajj_type'), choices=HAJJ_TYPES,
                                    null=True, blank=True)
    for_whom = models.IntegerField(_('for whom'), choices=WHOM, default=BOTH)
    time_interval = models.IntegerField(_('time interval in hours'),
                                        help_text=_('it depends on the category chosen'), null=True)
    lon = models.FloatField(_('longitude'), null=True, blank=True)
    lat = models.FloatField(_('latitude'), null=True, blank=True)

    class Meta:
        verbose_name = _('notification')
        verbose_name_plural = _('notifications')

    def __unicode__(self):
        return self.title

#class News(models.Model):
#    media =  models.ManyToManyField("Media" , blank=True)
#    header = models.CharField(_("Header") , max_length=255 , blank=True , null= True)
#    description = models.TextField(_("short description"), max_length=255, blank=True, null=True, help_text=_("short description of the image"))
#    pub_date    = models.DateTimeField(_("Created in"),help_text=_("Created in") , default = datetime.now() , editable = False)
#
#    def __unicode__(self):
#        return self.header
#
#    class Meta:
#        verbose_name = _('News')
#        verbose_name_plural = _('News')


class UserProfile(UserenaBaseProfile):
    MALE = 0
    FEMALE = 1
    GENDER = (
              (MALE, _('male')),
              (FEMALE, _('female')),
            )
    UMRAH = 0
    HAJJ_MUFRED = 1
    HAJJ_QAREN = 2
    HAJJ_MUTAMATE3 = 3
    MANASEK = (
               (UMRAH, _('umrah')),
               (HAJJ_MUFRED, _('hajj mufred')),
               (HAJJ_QAREN, _('hajj qaren')),
               (HAJJ_MUTAMATE3, _('hajj mutamate3')),
               )
    TENTH = 3
    ELEVNTH = 4
    TWELVTH = 5
    THIRTEENTH = 6
    DAYS = (
            (TENTH, _('tenth')),
            (ELEVNTH, _('eleventh')),
            (TWELVTH, _('twelvth')),
            (THIRTEENTH, _('thirteenth')),
            )
    user = models.OneToOneField(User, unique=True, verbose_name=_('user'), related_name='my_profile')
    current_time = models.DateTimeField(_("Current time"), help_text=_("Created in"), default=datetime.now(), editable=False)
    gender = models.IntegerField(_("Gender"), choices=GENDER, default=MALE)
#    location = models.CharField(_("Location"), max_length = 255, blank=True)
    time_to_travel = models.DateTimeField(_('time to travel'), blank=True, null=True)
    manasek_start_date = models.DateField(_('time to start manasek'), blank=True, null=True)
    type_of_mansak = models.IntegerField(_('mansak type'), choices=MANASEK, null=True, blank=True)
    tahallol_day = models.IntegerField(_('tahallol day'), help_text=_('which day to do the great tahallol'), choices=DAYS, blank=True, null=True)
    mota3agel = models.BooleanField(_('mot3agel'), blank=True)
    sa3ayt = models.BooleanField(help_text=_('in case you are doing hajj_qeran, did you "sa3ayt" just after umrah'))

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __unicode__(self):
        return ("%s %s") % (self.user.first_name, self.user.last_name)

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

    
    
    
    
    
    
    
    
    

src/userena/contrib/umessages/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from userena.contrib.umessages.fields import CommaSeparatedUserField
from userena.contrib.umessages.models import Message, MessageRecipient

import datetime

class ComposeForm(forms.Form):
    to = CommaSeparatedUserField(label=_("To"))
    body = forms.CharField(label=_("Message"),
                           widget=forms.Textarea({'class': 'message'}),
                           required=True)

    def save(self, sender):
        """
        Save the message and send it out into the wide world.

        :param sender:
            The :class:`User` that sends the message.

        :param parent_msg:
            The :class:`Message` that preceded this message in the thread.

        :return: The saved :class:`Message`.

        """
        to_user_list = self.cleaned_data['to']
        body = self.cleaned_data['body']

        msg = Message.objects.send_message(sender,
                                           to_user_list,
                                           body)

        return msg

src/userena/templates/form_snippet.html
{% for field in form.visible_fields %}
<div>

	{{ field.label_tag }}

	{{ field.errors }}

	{{ field }}
</div>
{% endfor %}


<style>
.errorlist{
    margin    : 0;

}
.errorlist li {
    background-color :red ;
    color : white ;
    list-display:none ;
    width : 220px;
 
}
.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
.ui-timepicker-div dl { text-align: left; }
.ui-timepicker-div dl dt { height: 25px; margin-bottom: -25px; }
.ui-timepicker-div dl dd { margin: 0 10px 10px 65px; }
.ui-timepicker-div td { font-size: 90%; }
.ui-tpicker-grid-label { background: none; border: none; margin: 0; padding: 0; }


</style>

src/userena/templates/hero.html
{% load i18n  %}
<!DOCTYPE html>

<!-- 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{{ LANGUAGE_CODE }}" lang="{{ LANGUAGE_CODE }}">
-->

<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>{% page_attribute page_title %}</title>
	<meta name="description" content="{% page_attribute meta_description %}"/>
	<meta name="keywords" content="{% page_attribute meta_keywords %}"/>


<script type="text/javascript" src="/static/js/jquery.js"></script> 
<link rel="stylesheet" href="/static/css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
    <!-- Le styles -->
    
    

<meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link href="{{ STATIC_URL }}css/bootstrap-rtl.css" rel="stylesheet">
  
    <link href="{{ STATIC_URL }}css/bootstrap-responsive-rtl.css" rel="stylesheet">
   
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->

    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ STATIC_URL }}ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ STATIC_URL }}ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}ico/apple-touch-icon-57-precomposed.png">
    
    
    {% render_block "css" %}
	{% render_block "js" %}
    
      <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      #cms_toolbar-toolbar{
      top:50px;
      }
    </style>
    
  </head>

  <body dir="rtl" id="{% block tpl_id %}none{% endblock %}" class="{{ LANGUAGE_CODE }}">

  
      <ul class="site-nav">
        <li><a href="/accounts/signin/">تسجيل الدخول</a></li>
       <li><a href="/accounts/signup/"> مستخدم جديد</a></li>
       {% if user.is_authenticated %}
        {% endif %}
        <li><a href="/events/events">المؤتمرات القادمة</a></li>
        <li class="last"><a href="/">الرئيسية</a></li>

           
              {% block navbar %}
              {% endblock navbar %}
              
      </ul>
      
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
    
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">المنسقية</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li ><a href="/">Home</a></li>
              <li><a href="/events/events">News</a></li>
              <li><a href="/news">News</a></li>
              {% block navbar %}
              {% endblock navbar %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div id="mycarousel" class="jcarousel">
        </div>
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
      {%block hero%}
      {%endblock hero%}
        
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
    
        </div>
        <div class="span4">
        {%block center-col%}
        {%endblock center-col%}
   
       </div>
        <div class="span4">
        {%block right-col%}
        {%endblock right-col%}
        

        </div>
      </div>

      <hr>
      <footer>

        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-transition.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-alert.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-modal.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-dropdown.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-scrollspy.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-tab.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-tooltip.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-popover.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-button.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-collapse.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-carousel.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-typeahead.js"></script>

  </body>
</html>

src/userena/templates/index.html
{% load i18n  %}
<!DOCTYPE html>

<!-- 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{{ LANGUAGE_CODE }}" lang="{{ LANGUAGE_CODE }}">
-->

<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>موقع نسك</title>


    <!-- Le styles -->
    
<link rel="stylesheet" href='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/flick/jquery-ui.css'
     type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />

<meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link href="{{ STATIC_URL }}css/bootstrap-rtl.css" rel="stylesheet">
  
    <link href="{{ STATIC_URL }}css/bootstrap-responsive-rtl.css" rel="stylesheet">
   
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->

    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ STATIC_URL }}ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ STATIC_URL }}ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}ico/apple-touch-icon-57-precomposed.png">
    
    

      <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;

      }
      .navbar .nav > li > a{
        color : white ;
        font-size : 16px;
      }
      .navbar-inner{

        background: #bfd255; /* Old browsers */
        background: -moz-linear-gradient(top,  #bfd255 0%, #8eb92a 50%, #72aa00 51%, #9ecb2d 100%); /* FF3.6+ */
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#bfd255), color-stop(50%,#8eb92a), color-stop(51%,#72aa00), color-stop(100%,#9ecb2d)); /* Chrome,Safari4+ */
        background: -webkit-linear-gradient(top,  #bfd255 0%,#8eb92a 50%,#72aa00 51%,#9ecb2d 100%); /* Chrome10+,Safari5.1+ */
        background: -o-linear-gradient(top,  #bfd255 0%,#8eb92a 50%,#72aa00 51%,#9ecb2d 100%); /* Opera 11.10+ */
        background: -ms-linear-gradient(top,  #bfd255 0%,#8eb92a 50%,#72aa00 51%,#9ecb2d 100%); /* IE10+ */
        background: linear-gradient(top,  #bfd255 0%,#8eb92a 50%,#72aa00 51%,#9ecb2d 100%); /* W3C */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#bfd255', endColorstr='#9ecb2d',GradientType=0 ); /* IE6-9 */

      }

      

    </style>
    
  </head>

  <body dir="rtl" id="{% block tpl_id %}none{% endblock %}" class="{{ LANGUAGE_CODE }}">

  
      
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
    
   
 
          <div class="nav-collapse" style="padding-right:20px;">
          
  
             <a class="brand" href="/accounts/{{request.user.username}}/"> نُسك </a>
        
            <ul class="nav">
       
          {% if user.is_authenticated %}
                <li><a href="/accounts/{{request.user.username}}/"  > الملف الشخصى </a></li>
              <li><a href="/accounts/signout/">تسجيل الخروج</a></li>

            {%else%}
            
              <li><a href="/accounts/signin/">تسجيل الدخول</a></li>
                <li><a href="/accounts/signup/"> مستخدم جديد</a></li>
                
            
        {%endif%}
       
              {% block navbar %}
              {% endblock navbar %}
              

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <div class="row">
        <div class="span2">
        {%block left-col%}
        
        {% if user.is_authenticated %}
                <div class="well">
        <ul class="nav nav-list">
        <li >
        <a href="{% url userena_profile_detail user.username %}"><span>{% trans 'View profile' %}</span></a>
        </li>
        <li ><a  href="{% url userena_profile_edit user.username %}">{% trans "Edit profile" %}</a></li>
        <li><a href="{% url userena_password_change user.username %}">{% trans "Change password" %}</a></li>
        <li ><a href="{% url userena_email_change user.username %}">{% trans "Change email" %}</a></li>
        </ul>
        </div>
        {% endif %}
        {%endblock left-col%}


        </div>
        <div class="span6">
        {%block center-col%}
        {%endblock center-col%}
   
       </div>
        <div class="span4">
        {%block right-col%}
        {%endblock right-col%}
        

        </div>
      </div>

      <footer>
    <center>
        <p>&copy; Company 2012</p>
    </center>
      </footer>
  </div>
 <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="/static/jquery.js"></script> 
    <script src= 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js' ></script>
    <script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/i18n/jquery-ui-i18n.min.js' ></script>
   <script src="{{ STATIC_URL }}timepicker.js"></script>
       <script>
    
    $(document).ready( function() {
           $.datepicker.setDefaults($.datepicker.regional['ar']);

    $('#id_time_to_travel').datetimepicker({
            dateFormat: 'yy-mm-dd',
            timeFormat: 'hh:mm:ss',
            currentText: 'الآن',
            closeText: 'تم التعديل',
         
    });
    $('#id_time_to_start_manasek').datetimepicker({
            dateFormat: 'yy-mm-dd',
            timeFormat: 'hh:mm:ss',
            currentText: 'الآن',
            closeText: 'تم التعديل',
            
    });
 
 });
    
    </script>
    
    
  </body>
</html>

src/userena/templates/layout.html
{% load i18n %}

{% block title %}{% trans "Email changed!" %}{% endblock %}

{% block content_title %}<h2>{% trans 'New email' %}</h2>{% endblock %}
{% block content %}
<p>{% blocktrans %}Your new email address is saved. You can continue using userena with this email.{% endblocktrans %}</p>
{% endblock %}